### ISSUE TITLE
Example from README returns "Malformed dice string" error

### ISSUE THREAD

**Issue by MatteoJoliveau** [oganm/dice_syntax_gd#9]
Hi! Thank you for this awesome module!

Unfortunately, I'm unable to run expressions that count successes, as I get a `Malformed dice string: Unprocessed token` error.

Here's what I'm trying to run (third example in the README.md):

```gdscript
print(dice_syntax.roll("4d6s>5", rng))
```

and here's the console output:

```
{ "result": 0, "rolls": [{ "error": true, "msg": ["Malformed dice string: Unprocessed tokens"], "dice": [], "drop": [], "result": 0 }], "error": true, "msg": ["Malformed dice string: Unprocessed tokens"] }
```

Am I missing something or doing something wrong? Thank you for your help!

**Comment by MatteoJoliveau** [comment]
Of course the moment I open this issue I figure it out 😅 

I'm running the addon installed from the AssetLib, which is still at version 2.2.2. Are there plans to release 3.0.0 in the AssetLib or should I just add it as git submodule to my project?

**Comment by oganm** [comment]
No worries. 3.0.0 should be up on the library sometime tomorrow. Currently waiting moderation, for godot 4 at least. Not sure if I'll be continuing to maintain the godot 3 version

**Comment by MatteoJoliveau** [comment]
Thank you @oganm, no rush I'll just import the library manually, for now, as I'm still prototyping.

Keep up the good job!
